config/routes.rb
Rails.application.routes.draw do
  resources :visitantes

  resources :visitantes do
    get '/page/:page', action: :index, on: :collection
  end


  root "visitantes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/visitante.rb
class Visitante < ApplicationRecord
  paginates_per 6
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/visitantes_controller.rb
class VisitantesController < ApplicationController
  before_action :set_visitante, only: %i[ show edit update destroy ]

  # GET /visitantes or /visitantes.json
  def index
    #@visitantes = Visitante.all
    @visitantes = Visitante.order(created_at: :desc).page params[:page]
  end

  # GET /visitantes/1 or /visitantes/1.json
  def show
  end

  # GET /visitantes/new
  def new
    @visitante = Visitante.new
  end

  # GET /visitantes/1/edit
  def edit
  end

  # POST /visitantes or /visitantes.json
  def create
    @visitante = Visitante.new(visitante_params)

    respond_to do |format|
      if @visitante.save
        format.html { redirect_to visitante_url(@visitante), notice: "Visitante was successfully created." }
        format.json { render :show, status: :created, location: @visitante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitantes/1 or /visitantes/1.json
  def update
    respond_to do |format|
      if @visitante.update(visitante_params)
        format.html { redirect_to visitante_url(@visitante), notice: "Visitante was successfully updated." }
        format.json { render :show, status: :ok, location: @visitante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visitante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitantes/1 or /visitantes/1.json
  def destroy
    @visitante.destroy

    respond_to do |format|
      format.html { redirect_to visitantes_url, notice: "Visitante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitante
      @visitante = Visitante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitante_params
      params.require(:visitante).permit(:foto, :nome, :descricao, :documento, :destino, :acompanhante, :estadia)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visitantes_helper.rb
module VisitantesHelper
end

app/views/layouts/_footer.html.erb
<div class="bg-[#1d1f2b] rounded-lg shadow">
    <hr class="w-full border-[#333549] shadow"/>
    <div class="h-2 px-24 py-10 flex items-center">
        <p id="footer-text" class="ml-5 text-[#93989a]">
            <a href="https://www.linkedin.com/in/alan-ramalho-4313771a9/">Alan Ramalho</a>, Todos os direitos reservados. 2022
        </p>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<div id="nav-full" class="bg-[#1d1f2b] rounded-lg shadow">
    <div id="nav-upbar" class="h-2 px-24 py-10 flex items-center cursor-pointer">
        <img id="nav-img" src="https://images.unsplash.com/photo-1546198632-9ef6368bef12?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80">
        <p id="nav-title" class="ml-5 text-xl font-semibold text-[#93989a]">Sistem para gerênciamento de visitantes</p>
        </div>

        <hr class="w-full border-[#333549] "/>
        <nav class="bg-gray-50 dark:bg-gray-700">
    <div class="py-3 px-4 mx-auto max-w-screen-xl md:px-6">
        <div class="flex items-center">
            <ul id="nav-menu" class="flex flex-row mt-0 mr-6 space-x-8 text-sm font-medium">
                <li>
                    <a href="<%= root_path %>" class="text-gray-900 dark:text-white">
                        INICIO
                    </a>
                </li>
                <li>
                    <a href="<%= new_visitante_path %>" class="text-gray-900 dark:text-white shadow bg-blue-600 ">
                        CADASTRAR
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<hr class="w-full border-[#333549] shadow"/>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerenciador de visitantes - v1.0</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.3/dist/flowbite.min.css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <header>
        <%= render "/layouts/navbar" %>
      </header>
        <section>

            <% if notice.present? %>
              <script>
                alert("<%= notice %>");
              </script>
            <% end %>


          <article class="lg:min-h-screen lh:flex lg:items-center p-6 lg:p-24 xl:-p40">

            <% if current_page?(root_path)%>
              <center><p class="text-white"> Listing: <%= @visitantes.all.count%> Item(s) </p></center>
            <% elsif current_page?("/visitantes/")%>
              <center><p class="text-white"> Listing: <%= @visitantes.all.count%> Item(s) </p></center>
            <% elsif current_page?("/visitantes/page/#{params[:page]}")%>
              <center><p class="text-white"> Listing: <%= @visitantes.all.count%> Item(s) </p></center>
            <% else %>

            <% end %>

            <div id="container" class="flex-grow shadow-2xl rounded-md border border-[#333549] p-2">
            <%= yield %>

            </div>
            <% if current_page?(root_path)%>
              <%= paginate @visitantes %>
            <% elsif current_page?("/visitantes/")%>
              <%= paginate @visitantes %>
            <% elsif current_page?("/visitantes/page/#{params[:page]}")%>
              <%= paginate @visitantes %>
            <% else %>

            <% end %>
            <br>

          </article>
        </section>
        <br>

    </main>
    <footer>
      <%= render "/layouts/footer" %>
    </footer>
  </body>
  <script src="../path/to/flowbite/dist/flowbite.js"></script>
</html>

app/views/visitantes/_form.html.erb
<div id="box-cadastro">

   <%= form_with(model: visitante, class: "form-cadastro contents") do |form| %>
   <% if visitante.errors.any? %>
   <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(visitante.errors.count, "error") %> prohibited this visitante from being saved:</h2>
      <ul>
         <% visitante.errors.each do |error| %>
         <li><%= error.full_message %></li>
         <% end %>
      </ul>
   </div>
   <% end %>
   <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
      <table class="w-full text-sm text-left text-black dark:text-gray-400">
         <thead class="text-xs text-black uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
               <th scope="col" class="py-3 px-6">
                  DESCRIÇÃO DO VISITANTE
               </th>
               <th scope="col" class="py-3 px-6">
                  OPÇÕES
               </th>
            </tr>
         </thead>
         <tbody>
            <tr class="bg-white dark:bg-gray-800">
               <th scope="row" class="py-4 px-6 font-medium text-black whitespace-nowrap">
                  <div class="my-5">
                     <%= form.label :nome %>
                     <%= form.text_field :nome, class: "block text-black shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
                  </div>
               </th>
               <td class="py-4 px-6">
                  <div class="my-5">
                     <% if current_page?(new_visitante_path) %>
                        <%= form.label :foto %>
                        <%= form.text_field :foto, rows: 4, class: "block text-black shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
                     <% else %>
                        <div class="flex">
                           <img  style="wdith: 120px; height: 120px;" src="<%= visitante.foto %>">
                           <%= form.text_field :foto, rows: 4, class: "block text-black shadow rounded-md border border-gray-200 outline-none  w-full" %>
                        </div>
                     <% end %>
                  </div>
               </td>
            </tr>
            <tr class="bg-white dark:bg-gray-800">
               <th scope="row" class="py-4 px-6 font-medium text-black whitespace-nowrap">
                  <div class="my-5">
                     <%= form.label :documento %>
                     <%= form.text_field :documento, class: "block text-black shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
                  </div>
               </th>
               <td class="py-4 px-6">
                  <div class="my-5">
                     <%= form.label :descricao %>
                     <%= form.text_field :descricao, class: "block text-black shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
                  </div>
               </td>
            </tr>
            <tr class="bg-white dark:bg-gray-800">
               <th scope="row" class="py-4 px-6 font-medium text-black whitespace-nowrap">
                  <div class="my-5">
                     <%= form.label :destino %>
                     <%= form.text_field :destino, class: "block text-black shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
                  </div>
               </th>
               <td class="py-4 px-6">
                  <div class="my-5">
                     <%= form.label :acompanhante %>
                     <%= form.text_field :acompanhante, class: "block text-black shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
                  </div>
               </td>
            </tr>
         </tbody>
      </table>
   </div>
   <div class="my-5">
      <%= form.label :estadia %>
      <%= form.datetime_field :estadia, class: "block text-black shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
   </div>

<div class="inline">
   <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
</div>
<% end %>

app/views/visitantes/_visitante.html.erb
<div id="visitor" class="border-2 border-slate-700 rounded-md shadow-xl h-40 bg-slate-800 max-w-lg m-5 flex justify-between">
  <a href="<%= visitante_path(visitante) %>" style="decoration: none;"><img src="<%= visitante.foto %>" alt="<%= visitante.nome %>" id="photo" class="h-32 w-32 m-4"></a>
  <div id="infos" class="rounded m-5 text-sm">
    <p>NOME: <%= visitante.nome %></p>
    <p>DOCUMENTO: <%= visitante.documento %></p>
    <p>DESTINO: <%= visitante.destino %></p>
    <p>ACOMPANHANTE: <%= visitante.acompanhante %></p>
    <p>ENTROU: <%= visitante.created_at %></p>
    <p>SAIDA: <%= visitante.estadia %></p>
  </div>

  <div id="card-buttons" class="rounded shadow-xl flex-col justify-between justify-center place-content-end border-2 border-slate-700 ">

    <div class="flex flex-col justify-between text-white">

      <% if current_page?(visitante_path(visitante))%>
        <style>
          #card-buttons {
            display: none;
          }
        </style>
      <% else %>
        <div class="show-btn">
          <a href="<%= visitante_path(visitante) %>">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 3.75v4.5m0-4.5h4.5m-4.5 0L9 9M3.75 20.25v-4.5m0 4.5h4.5m-4.5 0L9 15M20.25 3.75h-4.5m4.5 0v4.5m0-4.5L15 9m5.25 11.25h-4.5m4.5 0v-4.5m0 4.5L15 15" />
            </svg>

          </a>
        </div>
      <% end %>

    </div>

  </div>
</div>

<!--

<div id="visitante" class="shadow-2xl">
  <p class="my-5">
    <strong class="block font-medium mb-1">Foto:</strong>
    <%= visitante.foto %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Nome:</strong>
    <%= visitante.nome %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Descricao:</strong>
    <%= visitante.descricao %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Documento:</strong>
    <%= visitante.documento %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Destino:</strong>
    <%= visitante.destino %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Acompanhante:</strong>
    <%= visitante.acompanhante %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Estadia:</strong>
    <%= visitante.estadia %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this visitante", visitante, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this visitante', edit_visitante_path(visitante), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
  <% end %>
</div>-->

app/views/visitantes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">

  <%= render "form", visitante: @visitante %>

  <%= link_to "Show this visitante", @visitante, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to 'Back to visitantes', root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/visitantes/index.html.erb
<%= render @visitantes %>

app/views/visitantes/new.html.erb
<div id="buttons-box" class="mx-auto md:w-2/3 w-full">
  <center>

  <%= render "form", visitante: @visitante %>

  <%= link_to 'Back to visitantes', root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/visitantes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">

    <%= render @visitante %>

    <div id="control-box">

        <%= link_to 'Edit this visitante', edit_visitante_path(@visitante), class: "control-btn mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        <div class="inline-block ml-2">
          <%= button_to 'Destroy this visitante', visitante_path(@visitante), method: :delete, class: "control-btn mt-2 rounded-lg py-3 px-5 bg-blue-600 font-medium dark:text-white" %>
        </div>
        <%= link_to 'Back to visitantes', root_path, class: "control-btn ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

    </div>
  </div>
</div>